version: '2'

networks:
  app-tier:
    driver: bridge

services:
  strapi:
    image: jeyluu/strapi-svc-dnt:dev-0.2
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
      - JWT_SECRET=your-super-secret-key
      - ADMIN_JWT_SECRET=your-super-secret-key
      - TRANSFER_TOKEN_SALT=your-super-secret-key
      - APP_KEYS=your-super-secret-key
    ports:
      - "1337:1337"
    volumes:
      - ./strapi-cms-service:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-tier

  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=strapi
    networks:
      - app-tier
    ports:
      - "3306:3306"  # Forward MySQL port to localhost
    volumes:
      - mysql_data:/bitnami/mysql/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
